#    __    __  __    __   __    ______   ______   __    ______    __   __   
#   /\ \  /\ \/\ \  /\ "-.\ \  /\  ___\ /\__  _\ /\ \  /\  __ \  /\ "-.\ \  
#  _\_\ \ \ \ \_\ \ \ \ \-.  \ \ \ \____\/_/\ \/ \ \ \ \ \ \/\ \ \ \ \-.  \ 
# /\_____\ \ \_____\ \ \_\\"\_\ \ \_____\  \ \_\  \ \_\ \ \_____\ \ \_\\"\_\
# \/_____/  \/_____/  \/_/ \/_/  \/_____/   \/_/   \/_/  \/_____/  \/_/ \/_/

# Enable debugging mode for detailed logs
debug: false

# Automatically assign players on Bedrock Edition to a specified group
permissions:
  enabled: true

  # Which permission plugin to use
  # Supported: "LuckPerms" or "Vault"
  provider: "LuckPerms"

  # Group assignment for Bedrock Edition players
  # Note: The specified group must already exist in your permission plugin!
  group: "bedrock"

# Do not touch this!
config-version: 1